engines:
  csslint:
    enabled: true
  pep8:
    enabled: true
  eslint:
    enabled: true
  duplication:
    enabled: true
    exclude_fingerprints:
    - df955cfb2c96fb691d452179a6be87dc # Float comparisons
    - 8733798df05b069e56b46c3018b38657 # Int comparisons
    - 5e4153a895bd84772d47eeb39ea876f5
    config:
      languages:
        python:
          mass_threshold: 40
        javascript:
          mass_threshold: 40

ratings:
  paths:
  - argux_server/**

exclude_paths:
  - "tests/**"
  - "argux_server/static/js/lib/debug/*.js"
  - "argux_server/static/js/lib/*.js"
  - "argux_server/static/js/debug/*.js"
  - "argux_server/static/js/ext/*.js"
  - "argux_server/static/js/*.js"
  - "argux_server/static/css/debug/*.css"
  - "argux_server/static/css/ext/*.css"
  - "argux_server/static/css/*.css"
