engines:
  csslint:
    enabled: true
  pep8:
    enabled: true
  eslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        python:
          mass_threshold: 40
        javascript:
          mass_threshold: 40

ratings:
  paths:
  - argux_server/**

exclude_paths:
  - "tests/**"
  - "argux_server/static/js/debug/*.js"
  - "argux_server/static/js/ext/*.js"
  - "argux_server/static/js/*.js"
  - "argux_server/static/css/debug/*.css"
  - "argux_server/static/css/ext/*.css"
  - "argux_server/static/css/*.css"
