language: node
node_js: 
  - 4
addons:
  apt:
    packages:
      - python3
before_install:
  - pyvenv-3.4 build
  - . ./build/bin/activate
install:
  - pip install nose
  - pip install coveralls
  - python setup.py install
  - npm install
  - argux-server_initdb tests/test.ini

# command to run tests, e.g. python setup.py test
script: ./run_tests.sh

after_success:
  coveralls

sudo: false
