language: python
python:
  - "3.3"
install:
  - pip install nose
  - pip install coveralls
  - python setup.py install
  - argux-server_initdb development.ini

# command to run tests, e.g. python setup.py test
script:
  nosetests --with-coverage --cover-package argux_server

after_success:
  coveralls

sudo: false
