language: python
python:
  - "3.3"
install:
  - pip install nose
  - pip install coveralls
  - python setup.py install
  - argux-server_initdb tests/test.ini

# command to run tests, e.g. python setup.py test
script:
  python setup.py nosetests

after_success:
  coveralls

sudo: false
