language: python
python:
  - "3.3"
install:
  - pip install nose
  - pip install coveralls
  - python setup.py install
  - initialize_argux-server_db development.ini

# command to run tests, e.g. python setup.py test
script:
  nosetests --with-coverage --cover-package arguxserver

after_success:
  coveralls

sudo: false
